# Generated by Django 4.0.4 on 2022-05-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isUpdated',
            field=models.BooleanField(default=False),
        ),
    ]
